/* Odd Two Out: five words, three are related, find the two that don't belong.
 *
 * Each question: { id, source, words: [5], answer: [w1, w2], explain (HTML), hint }
 * Bank entries are written as q(words, oddPair, whyGroup, whyOdd) and expanded below.
 */
(function (global) {
  'use strict';

  const rand = (n) => Math.floor(Math.random() * n);
  const shuffle = (arr) => {
    const a = arr.slice();
    for (let i = a.length - 1; i > 0; i--) {
      const j = rand(i + 1);
      [a[i], a[j]] = [a[j], a[i]];
    }
    return a;
  };

  let counter = 0;
  // tricky: true when the question has a trap (a double meaning, or a topic that is not a group).
  function q(words, odd, whyGroup, whyOdd, tricky) {
    const group = words.filter((w) => !odd.includes(w));
    if (group.length !== 3 || odd.length !== 2) throw new Error('Bad odd-two-out question: ' + words.join(' '));
    counter += 1;
    return {
      id: 'odd-' + counter,
      source: 'Practice',
      tricky: !!tricky,
      words,
      answer: odd,
      hint: `${group[rand(3)]} is one of the three that go together. Find its two friends, then the leftovers are your answer.`,
      explain:
        `<p><strong>The three that go together:</strong> ${group.join(', ')}.</p>` +
        `<p>${whyGroup}</p>` +
        `<p><strong>The odd two out:</strong> ${odd.join(' and ')}.</p>` +
        `<p>${whyOdd}</p>`,
    };
  }

  /* ---------- Practice bank ----------
   * Questions marked tricky carry a trap.
   */
  const BANK = [
    q(['purple', 'blue', 'crow', 'beach', 'brown'], ['crow', 'beach'],
      'Purple, blue and brown are all colours.',
      'A crow is a bird and a beach is a place. Watch out for words that sound like they might fit: crow is not a colour, even though "crow black" sounds like one.',
      true),
    q(['blunt', 'pencil', 'point', 'dull', 'unsharpened'], ['pencil', 'point'],
      'Blunt, dull and unsharpened all describe something that is not sharp.',
      'Pencil and point are things, not descriptions. They are tempting because you sharpen a pencil to a point, but the test wants the three words that mean the same kind of thing.',
      true),
    q(['cost', 'fee', 'money', 'change', 'price'], ['money', 'change'],
      'Cost, fee and price all mean the amount you have to pay for something.',
      'Money is what you pay with, and change is what you get back. They are about money, but they are not amounts you are charged. This is the trap: pick the three that mean the same thing, not the five that share a topic.',
      true),
    q(['house', 'address', 'door', 'lecture', 'speech'], ['house', 'door'],
      'Address, lecture and speech are all talks given to an audience.',
      'House and door are parts of a building. Address is the trick word: it can mean where you live, but it also means a formal speech, and that is the meaning that fits here.',
      true),
    q(['second', 'decade', 'third', 'fortnight', 'agree'], ['third', 'agree'],
      'Second, decade and fortnight are all lengths of time.',
      'Third is a position (first, second, third) and agree is a verb. Second is the trap: it looks like it pairs with third, but here it means a unit of time, so it belongs with decade and fortnight.',
      true),
    q(['crisp', 'hot', 'scorching', 'icy', 'freezing'], ['hot', 'scorching'],
      'Crisp, icy and freezing all describe cold weather.',
      'Hot and scorching are the opposite. Crisp is the tricky one: a crisp morning is a cold, fresh one, so it belongs with the cold words. When two words obviously pair up, check whether the other three share something too.',
      true),
    q(['travel', 'follow', 'lead', 'guide', 'escort'], ['travel', 'follow'],
      'Lead, guide and escort all mean to show someone the way, going in front of them.',
      'Travel just means to go somewhere, and follow means to go behind, which is the opposite of leading.',
      true),
    q(['brave', 'courageous', 'battle', 'hero', 'valiant'], ['battle', 'hero'],
      'Brave, courageous and valiant all mean the same thing: showing courage.',
      'Battle and hero are nouns from the same topic, but they are things, not describing words. Same topic is not the same as same meaning.',
      true),
    q(['apple', 'banana', 'carrot', 'cherry', 'potato'], ['carrot', 'potato'],
      'Apple, banana and cherry are all fruits.',
      'Carrot and potato are vegetables.'),
    q(['run', 'sprint', 'jog', 'sit', 'stand'], ['sit', 'stand'],
      'Run, sprint and jog are all ways of moving quickly on foot.',
      'Sit and stand are ways of staying still.'),
    q(['hammer', 'saw', 'nail', 'drill', 'screw'], ['nail', 'screw'],
      'Hammer, saw and drill are all tools.',
      'Nail and screw are things you use tools on, not tools themselves.', true),
    q(['oak', 'ash', 'elm', 'rose', 'daisy'], ['rose', 'daisy'],
      'Oak, ash and elm are all trees.',
      'Rose and daisy are flowers.'),
    q(['happy', 'cheerful', 'glum', 'joyful', 'miserable'], ['glum', 'miserable'],
      'Happy, cheerful and joyful all mean feeling good.',
      'Glum and miserable mean feeling sad, the opposite.'),
    q(['whisper', 'shout', 'murmur', 'mutter', 'yell'], ['shout', 'yell'],
      'Whisper, murmur and mutter are all quiet ways of speaking.',
      'Shout and yell are loud.'),
    q(['minute', 'hour', 'clock', 'week', 'watch'], ['clock', 'watch'],
      'Minute, hour and week are all lengths of time.',
      'Clock and watch are things that measure time, not amounts of it.'),
    q(['trout', 'salmon', 'cod', 'seal', 'whale'], ['seal', 'whale'],
      'Trout, salmon and cod are all fish.',
      'Seal and whale live in the sea but they are mammals, not fish.', true),
    q(['sofa', 'chair', 'bench', 'table', 'desk'], ['table', 'desk'],
      'Sofa, chair and bench are all things you sit on.',
      'Table and desk are things you put things on.', true),
    q(['red', 'crimson', 'scarlet', 'navy', 'indigo'], ['navy', 'indigo'],
      'Red, crimson and scarlet are all shades of red.',
      'Navy and indigo are shades of blue.'),
    q(['huge', 'enormous', 'tiny', 'vast', 'minute'], ['tiny', 'minute'],
      'Huge, enormous and vast all mean very big.',
      'Tiny and minute mean very small. Minute is the trap: here it is pronounced my-NUTE and means tiny, not sixty seconds.', true),
    q(['begin', 'start', 'finish', 'commence', 'end'], ['finish', 'end'],
      'Begin, start and commence all mean to get something going.',
      'Finish and end are the opposite.'),
    q(['tulip', 'lily', 'oak', 'pine', 'daffodil'], ['oak', 'pine'],
      'Tulip, lily and daffodil are all flowers.',
      'Oak and pine are trees.'),
    q(['spoon', 'fork', 'knife', 'plate', 'bowl'], ['plate', 'bowl'],
      'Spoon, fork and knife are all cutlery, things you eat with.',
      'Plate and bowl are things you eat from.'),
    q(['Paris', 'Rome', 'France', 'Madrid', 'Spain'], ['France', 'Spain'],
      'Paris, Rome and Madrid are all capital cities.',
      'France and Spain are countries.'),
    q(['cat', 'dog', 'kitten', 'puppy', 'cub'], ['cat', 'dog'],
      'Kitten, puppy and cub are all names for young animals.',
      'Cat and dog are the grown-up animals.', true),
    q(['car', 'lorry', 'van', 'bicycle', 'tricycle'], ['bicycle', 'tricycle'],
      'Car, lorry and van all have engines.',
      'Bicycle and tricycle are powered by pedalling.'),
    q(['gold', 'silver', 'bronze', 'ruby', 'emerald'], ['ruby', 'emerald'],
      'Gold, silver and bronze are all metals (and the three medals).',
      'Ruby and emerald are gemstones.'),
    q(['giggle', 'chuckle', 'sob', 'laugh', 'weep'], ['sob', 'weep'],
      'Giggle, chuckle and laugh are all ways of laughing.',
      'Sob and weep are ways of crying.'),
    q(['mansion', 'cottage', 'bungalow', 'garage', 'shed'], ['garage', 'shed'],
      'Mansion, cottage and bungalow are all houses that people live in.',
      'Garage and shed are buildings for storing things.'),
    q(['ancient', 'old', 'modern', 'elderly', 'new'], ['modern', 'new'],
      'Ancient, old and elderly all mean having been around a long time.',
      'Modern and new are the opposite.'),
    q(['sparrow', 'robin', 'bat', 'wren', 'moth'], ['bat', 'moth'],
      'Sparrow, robin and wren are all birds.',
      'Bat and moth can fly, but a bat is a mammal and a moth is an insect.', true),
    q(['triangle', 'square', 'circle', 'cube', 'sphere'], ['cube', 'sphere'],
      'Triangle, square and circle are all flat (2D) shapes.',
      'Cube and sphere are solid (3D) shapes.'),
    q(['teacher', 'pupil', 'doctor', 'nurse', 'patient'], ['pupil', 'patient'],
      'Teacher, doctor and nurse are all jobs.',
      'Pupil and patient are the people being taught or treated, not jobs.', true),
    q(['rain', 'snow', 'hail', 'sun', 'wind'], ['sun', 'wind'],
      'Rain, snow and hail all fall from the sky.',
      'Sun and wind are weather too, but nothing falls.', true),
    q(['stroll', 'wander', 'dash', 'amble', 'hurry'], ['dash', 'hurry'],
      'Stroll, wander and amble all mean to walk slowly and casually.',
      'Dash and hurry mean to move fast.'),
    q(['novel', 'poem', 'story', 'author', 'reader'], ['author', 'reader'],
      'Novel, poem and story are all pieces of writing.',
      'Author and reader are people.', true),
    q(['flour', 'sugar', 'butter', 'oven', 'bowl'], ['oven', 'bowl'],
      'Flour, sugar and butter are all ingredients.',
      'Oven and bowl are equipment you use when baking.', true),
    q(['brief', 'short', 'lengthy', 'quick', 'long'], ['lengthy', 'long'],
      'Brief, short and quick all mean not taking much time.',
      'Lengthy and long are the opposite.'),
    q(['violin', 'cello', 'guitar', 'trumpet', 'flute'], ['trumpet', 'flute'],
      'Violin, cello and guitar all have strings.',
      'Trumpet and flute are played by blowing.'),
    q(['hungry', 'starving', 'full', 'famished', 'satisfied'], ['full', 'satisfied'],
      'Hungry, starving and famished all mean wanting food.',
      'Full and satisfied mean you have had enough.'),
    q(['lion', 'tiger', 'leopard', 'zebra', 'giraffe'], ['zebra', 'giraffe'],
      'Lion, tiger and leopard are all big cats.',
      'Zebra and giraffe are African animals too, but they are not cats.', true),
    q(['kind', 'cruel', 'gentle', 'harsh', 'caring'], ['cruel', 'harsh'],
      'Kind, gentle and caring all describe someone who is nice to others.',
      'Cruel and harsh are the opposite.'),
    q(['river', 'stream', 'brook', 'lake', 'pond'], ['lake', 'pond'],
      'River, stream and brook are all flowing water.',
      'Lake and pond are still water.'),
    q(['leap', 'jump', 'crawl', 'bound', 'creep'], ['crawl', 'creep'],
      'Leap, jump and bound all mean to spring off the ground.',
      'Crawl and creep mean to move low and slowly.'),
    q(['rich', 'wealthy', 'poor', 'prosperous', 'needy'], ['poor', 'needy'],
      'Rich, wealthy and prosperous all mean having plenty of money.',
      'Poor and needy are the opposite.'),
    q(['mend', 'repair', 'fix', 'break', 'damage'], ['break', 'damage'],
      'Mend, repair and fix all mean to make something work again.',
      'Break and damage are the opposite.'),
    q(['jacket', 'coat', 'scarf', 'anorak', 'gloves'], ['scarf', 'gloves'],
      'Jacket, coat and anorak are all things you wear over your body to keep warm.',
      'Scarf and gloves are worn on your neck and hands.'),
    q(['ask', 'enquire', 'question', 'answer', 'reply'], ['answer', 'reply'],
      'Ask, enquire and question all mean to try to find something out.',
      'Answer and reply are what you do in response.'),
    q(['pound', 'dollar', 'euro', 'wallet', 'purse'], ['wallet', 'purse'],
      'Pound, dollar and euro are all types of money.',
      'Wallet and purse are things you keep money in.', true),
    q(['lemon', 'lime', 'grapefruit', 'pear', 'plum'], ['pear', 'plum'],
      'Lemon, lime and grapefruit are all citrus fruits.',
      'Pear and plum are fruits too, but not citrus. When all five share a topic, look for the tighter group.', true),
    q(['brave', 'timid', 'bold', 'fearless', 'shy'], ['timid', 'shy'],
      'Brave, bold and fearless all mean not afraid.',
      'Timid and shy are the opposite.'),
    q(['shirt', 'blouse', 'jumper', 'trousers', 'shorts'], ['trousers', 'shorts'],
      'Shirt, blouse and jumper are all worn on the top half of your body.',
      'Trousers and shorts are worn on your legs.'),
    q(['hill', 'mountain', 'peak', 'valley', 'ditch'], ['valley', 'ditch'],
      'Hill, mountain and peak are all high ground.',
      'Valley and ditch are low ground.'),
    q(['bakery', 'butcher', 'florist', 'bread', 'meat'], ['bread', 'meat'],
      'Bakery, butcher and florist are all shops.',
      'Bread and meat are things sold in shops.', true),
    q(['quiet', 'silent', 'noisy', 'hushed', 'loud'], ['noisy', 'loud'],
      'Quiet, silent and hushed all mean with little or no sound.',
      'Noisy and loud are the opposite.'),
    q(['daybreak', 'dawn', 'sunrise', 'dusk', 'sunset'], ['dusk', 'sunset'],
      'Daybreak, dawn and sunrise all mean the start of the day.',
      'Dusk and sunset are the end of the day.'),
    q(['copper', 'brass', 'steel', 'marble', 'granite'], ['marble', 'granite'],
      'Copper, brass and steel are all metals.',
      'Marble and granite are types of stone.'),
    q(['exhausted', 'tired', 'weary', 'lively', 'energetic'], ['lively', 'energetic'],
      'Exhausted, tired and weary all mean having no energy left.',
      'Lively and energetic are the opposite.'),
    q(['scissors', 'knife', 'blade', 'ruler', 'pencil'], ['ruler', 'pencil'],
      'Scissors, knife and blade are all things that cut.',
      'Ruler and pencil are for measuring and writing.'),
    q(['ship', 'yacht', 'ferry', 'harbour', 'anchor'], ['harbour', 'anchor'],
      'Ship, yacht and ferry are all boats.',
      'Harbour and anchor are to do with boats, but they are not boats.', true),
    q(['furious', 'angry', 'calm', 'cross', 'peaceful'], ['calm', 'peaceful'],
      'Furious, angry and cross all mean annoyed.',
      'Calm and peaceful are the opposite.'),
    q(['carpenter', 'plumber', 'electrician', 'hammer', 'spanner'], ['hammer', 'spanner'],
      'Carpenter, plumber and electrician are all trades, people who do a job.',
      'Hammer and spanner are tools they might use.', true),
    q(['bread', 'roll', 'loaf', 'butter', 'jam'], ['butter', 'jam'],
      'Bread, roll and loaf are all baked bread.',
      'Butter and jam are things you spread on bread.'),
    q(['pupil', 'student', 'learner', 'lesson', 'classroom'], ['lesson', 'classroom'],
      'Pupil, student and learner are all people who are learning.',
      'Lesson and classroom are things, not people.', true),
    q(['odd', 'strange', 'normal', 'peculiar', 'usual'], ['normal', 'usual'],
      'Odd, strange and peculiar all mean unusual.',
      'Normal and usual are the opposite.'),
    q(['thrilled', 'delighted', 'bored', 'overjoyed', 'weary'], ['bored', 'weary'],
      'Thrilled, delighted and overjoyed all mean extremely pleased.',
      'Bored and weary mean fed up or tired.'),
    q(['fib', 'lie', 'truth', 'untruth', 'fact'], ['truth', 'fact'],
      'Fib, lie and untruth all mean something said that is not true.',
      'Truth and fact are the opposite.'),
    q(['pier', 'jetty', 'quay', 'beach', 'cliff'], ['beach', 'cliff'],
      'Pier, jetty and quay are all built structures where boats stop.',
      'Beach and cliff are natural parts of the coast.', true),
    q(['book', 'volume', 'novel', 'page', 'chapter'], ['page', 'chapter'],
      'Book, volume and novel are all whole books.',
      'Page and chapter are parts of a book. Whole things and parts of things are a common trap.', true),
    q(['gale', 'breeze', 'gust', 'drizzle', 'shower'], ['drizzle', 'shower'],
      'Gale, breeze and gust are all kinds of wind.',
      'Drizzle and shower are kinds of rain.'),
  ];

  /* ---------- Draw from the bank without repeats until it runs out ---------- */
  // Separate decks for "all" and "tricky only", each drawn without repeats until empty.
  const decks = { all: [], tricky: [] };
  function next(filter) {
    const key = filter === 'tricky' ? 'tricky' : 'all';
    if (decks[key].length === 0) decks[key] = shuffle(key === 'tricky' ? BANK.filter((b) => b.tricky) : BANK);
    const base = decks[key].pop();
    // Shuffle the word order each time so he can't learn positions.
    return Object.assign({}, base, { words: shuffle(base.words) });
  }

  global.OddTwoOut = { next, bankSize: BANK.length, trickySize: BANK.filter((b) => b.tricky).length };
})(window);
